=head1 NAME

Netdisco INSTALL -- Instructions for setting up Netdisco application.

=head1 VERSION

Netdisco 0.94

B<PLEASE> check the latest version of this document at 
L<http://netdisco.org/install.html> in case of bugs.

=head1 AUTHOR

Created by Max Baker.

See list at the end of README of all the contributors.

=head1 SUPPORT

Netdisco is hosted by Source Forge.

Please use the C<netdisco-users> mailing list for all problems and comments.

L<http://lists.sourceforge.net/lists/listinfo/netdisco-users>

Please use the Bug interface from Source Forge page at :

L<http://sourceforge.net/projects/netdisco>

=head1 REQUIREMENTS

Netdisco is built using lots of fine Open-Source tools: 

=over

=item * Perl

5.6.1 and newer advised.  

5.8.1 on Mandrake 9.x may be a problem (if you get
an C<out of memory> error, you may need to change to 
5.6.1 or 5.8.2).

=item * Perl Modules

Listed below

=item * Net-SNMP

5.0.2 and newer advised.  Untested on 5.1.x

=item * PostgreSQL

Version 7.4 B<strongly> recommended.  

Reported working for versions 7.2, 7.3, 7.4

=item * Mason

1.16 or newer required

=item * Apache

1.3.x advised, Version 2.x not supported by mod_perl.

=item * mod_perl   

Version to match Apache - 1.28 or higher recommended. 

Do not install version 1.99.

=item * GraphViz (Optional)

Version 0.12 or higher recommended.

=back

See I<INSTALL> below for details on how to retrieve and install each one.

=head2 OS

Netdisco was developed on a FreeBSD system but should work on any
system that Postgres, Perl, Apache, and Net-SNMP run on. 

Linux is a sure bet.  Netdisco has been tested with Mandake 9.1 
and includes specific notes to install with it.  Successful installs
have been reported under Redhat, Mandrake, Gentoo and Debian.

One user has reported getting Netdisco running on OS X.

Windows will take a lot of massaging but should be possible under
Cygwin.

=head1 INSTALL

This is not a terribly easy install.  If you aren't comfortable installing
programs from source and using a text editor, get some help.  Hopefully this
will all be rolled up into an install script by the time Netdisco hits
version 1.0.

=head2 1. Download and Un-archive Netdisco

Get the newest version from L<http://www.netdisco.org>.

    tar xvfz netdisco-x.xx.tar.gz    

Create a directory for Netdisco 

    mkdir /usr/local/netdisco

Move files to that dir

    mv netdisco-x.xx/* /usr/local/netdisco

=head3 Non-Standard install Directory


If you plan to install to a directory other than C</usr/local/netdisco> then you must
change a couple files.  Otherwise Skip down to Number 2.

=over

=item SQL Shell Scripts


Modify the following shell scripts :

    sql/pg_run
    sql/pg_init
    sql/pg_back

=item netdisco.conf

Double-check the C<home> option in F<netdisco.conf>.

=item netdisco_apache.conf

Change all the appearances of C</usr/local/netdisco> in F<netdisco_apache.conf>
to match your new directory.

=item netdisco_apache_dir.conf

Change all the appearances of C</usr/local/netdisco> in F<netdisco_apache_dir.conf>
to match your new directory.

=back

=head2 2. Create a Unix User/Group for Netdisco  

Create a user and group named C<netdisco>

=over

=item Linux

    useradd -d /usr/local/netdisco netdisco

=item BSD

    adduser netdisco

=back

Give this user permission to the files:

    chown -R netdisco.netdisco /usr/local/netdisco

=head2 3. Add Unix Administrators to Netdisco Group

Once Netdisco is up and running most administration
can be done from the Web interface.  Whoever will be doing
the back-end administration will need to have write access and will need
write access on Netdisco's files.

Add the unix account names of administrators that will modify the 
source code or use the command line interface interface to the C<netdisco>
group in F</etc/groups>.

Don't forget to logout and login after adding yourself to a group.

=head2 4. PostgreSQL

Netdisco runs Postgres as its database back-end.  A mySQL port 
is reported to be in development.

=head3 4.1.  Install Postgres

=over

=item [4.1.1] BSD 

First install Postgres from ports:

    cd /usr/ports/database/postgresql7
    gmake install

Next initialize the database :

    more /usr/local/pgsql/post-install-notes
    su -l pgsql -c initdb 

=item [4.1.2] Mandrake Linux

Installing PostgreSQL the easy way:

    urpmi postgresql postgresql-devel postgresql-server postgresql-docs

The files you will need to edit below are in F</var/lib/pgsql/data>.

If you lost / don't have install CDs :

The following line uses an FTP site that has the 9.0 RPMs because I lost
the CDs.  Check the current mirror list at L<http://www.mandrakelinux.com/en/ftp.php3>
and choose a mirror close to you.

    urpmi.addmedia ftpsite ftp://mirror.mcs.anl.gov/pub/Mandrake-old/9.0/i586/Mandrake/RPMS \
        with ../base/hdlist.cz

Now you have to add C<--media ftpsite>  in each C<urpmi> command like so :

    urpmi --media ftpsite postgresql postgresql-devel

Remember this for the Apache setup too.

=item [4.1.3] MAC OS X

See L<http://developer.apple.com/internet/macosx/postgres.html> for detailed instructions
on installing PostgreSQL with OS X.

=item [4.1.4] By Source (All Others)

There is probably a binary package all ready for you.  See your distribution's instructions
for more help.  Otherwise download and compile the source code from L<http://www.postgresql.org>.

If you are installing Postgres from source you may have to run these two commands in order
to install the DBD::Pg Perl module later on :

    export POSTGRES_INCLUDE=/usr/local/postgres/include
    export POSTGRES_LIB=/usr/local/postgres/lib

You may also have to modify your F</etc/ld.so.conf> to include your new POSTGRES_LIB directory.
Don't forget to run C<ldconf> afterwards.

=back

=head3 4.2.  Configure Postgres

Netdisco's settings in PostgreSQL are

 Database User     : netdisco
 Database Name     : netdisco
 Database Password : you choose it

Follow these steps to setup Netdisco in PostgreSQL.

=over 

=item [4.2.1] Permissions

If you have just setup Postgres for the first time you may have to change the
default permissions in F<$PG_DATA/pg_hba.conf>.  $PG_DATA might be in F</usr/local/pgsql> or in
F</var/db>, depends on your OS.  Check the postgres users' homedir files for the location of $PG_DATA.

For installation you must give the database user access to the C<template1> database.
The following line will give all users who have logon permissions in Unix access
to the C<template1> database.

    local template1 all ident

Next you must give the C<netdisco> database user access to the C<netdisco> database.
The following line will give all database users access to a database that is the same
name as them.  This line must be put above all the rest of the uncommented lines in the
F<pg_hba.conf> file to take precedence.  

    local sameuser all md5

You may have to swap C<md5> for C<crypt>, for old versions of Postgres.
Upgrade.

Finally if you would like to have root be able to access all databases,
try this one :

    local all root trust

=item [4.2.2] Restart Postgres

You must now restart Postgres

Linux :

    /etc/rc.d/init.d/postgresql restart

FreeBSD :
    
    /usr/local/etc/rc.d/*pgsql* restart

If there are problems with this step you will receive an error that mentions something
about F<pg_hba.conf>.

=item [4.2.3] Create Database.

Make sure your copy of the database is running.

Next, find out the name of your database user.  The default name for
some Linux RPM versions is C<postgres> and for some BSD installations C<pgsql>.

Edit the file C<pg_init> to match your database user name in F</usr/local/netdisco/sql/pg_init>

    vi /usr/local/netdisco/sql/pg_init

As root run C<sql/pg_init> to create the database and user for Netdisco.

The password you will be asked for twice is the new password for the database user you are creating. 
This is the same password you will be putting in F<netdisco_apache.conf>
and in F<netdisco.conf>.

    cd /usr/local/netdisco/sql
    ./pg_init

=item [4.2.4] Check Settings

Now as a non-privileged user make sure you can get into the database by running 
C<sql/pg_run>.  Enter the database user password given above. 

    cd /usr/local/netdisco/sql
    ./pg_run

=item [4.2.5] Create Tables

Once you are sure the database is setup correctly, create the database 
tables with C<sql/pg_all>.  Type in the database user password once 
when prompted.

    cd /usr/local/netdisco/sql
    ./pg_all

=item [4.2.6] Optimizations

If you have freshly installed Postgresql then the default memory usage B<NEEDS> to
be increased for efficiency.  See the PostgreSQL documentation for 
F<postgresql.conf>.  

Specifically you really need to up the maximum connections and shared memory
settings.  After you have Netdisco running on a large installation it would be
of great benefit to get a Postgres guru in there to tune things for you.  See
F<README> for more info about how to speed things up now and again.

=item [4.2.7] Postgres Startup

Make sure that Postgres is set to start automatically.

=over

=item Linux


    chkconfig postgresql on

=item BSD

Make sure that the file in C</usr/local/etc/rc.d> is alright.

=back

=item [4.2.8] Postgres Maintenance

Read the section in F<README> about Database Maintenance... every once in a
while you may have to run a C<VACUUM> and C<REINDEX> by hand if things get too slow.

=item [4.2.9] Remote Database (Optional)

If you have postgres installed in a remote location then all you have
to do is add that host information to the C<db_Pg> line in F<netdisco.conf>.

    db_Pg = dbi:Pg:dbname=netdisco;host=HOSTNAME;port=PORT;

On the Postgresql machine, allow your remote front end to contact the backend
database. Here is a sample line in F<pg_hba.conf>.

 #TYPE  DATABASE          USER            IP-ADDRESS              IP-MASK           METHOD
 host   netdisco        netdisco         101.102.103.104         255.255.255.0       md5

Don't forget to restart Postgres after changing the F<pg_hba.conf> file.

=back

=head2 5. SNMP

There are three components to setup for SNMP

=head3 5.1.  Net-SNMP

Net-SNMP 5 lives at L<http://net-snmp.sourceforge.net>.

See OS-specific notes below.

=over

=item [5.1.1] Download Net-SNMP from http://net-snmp.sourceforge.net

This used to be called ucd-snmp.

=item [5.1.2] Install Net-SNMP to include Perl module that comes inside the distribution.

When you run C<./configure>, make sure you add the switch C<--with-perl-modules>

    ./configure --with-perl-modules --enable-shared
    make 
    make install

If you already have net-snmp installed, then go to the source directory and 
in the C<perl> subdirectory and run C<perl Makefile.PL>

    cd /path/to/net-snmp-5.0.x/perl
    perl Makefile.PL
    make
    make install


 ********************************************************************

B<DO NOT> INSTALL the SNMP:: modules off of CPAN or the NET::SNMP module off of CPAN.

 ********************************************************************

Reread the above line.

=item [5.1.3] (Optional) Configure Net-SNMP for a non-standard setup

You probably will not have to do this step unless you have installed 
net-snmp somewhere other than F</usr/local/> or have some specific SNMP defaults to change 
for these tools. 

    snmpconf

Make sure to set the MIB dir if non-standard or you are 
not using the MIBS that come with Netdisco. 

 (Textual mib Parsing -> Specifies directories to be searched for mibs) 

Make sure this newly created F<snmp.conf> lives in F</usr/local/share/snmp> or wherever you
put a custom install.

=back

OS Specific Notes : 

=over

=item BSD

For BSD install Net SNMP with ports :

    cd /usr/ports/net/net-snmp && make install

For a recent version of BSD you should get the Perl modules installed automatically.

For a really old version, or for weird and multiple Perl installs do it by hand!

    cd /usr/ports/net/net-snmp
    make
    cd work/net-snmp-5
    ./configure --with-perl-modules
    make
    make install

=item Linux

If you have installed the Net-SNMP RPM from Redhat or Mandrake it B<does not> include 
the Perl modules.  B<Uninstall it> and install a newer version by hand as below.

    rpm -e net-snmp

Same goes for Debian.  DO NOT use the apt-get version of Net-SNMP,
install by hand (it's easy!).

=back

=head3 5.2.  SNMP::Info

This Perl module is an integral part of Netdisco.  It is available
from L<http://snmp-info.sourceforge.net>.   It requires that you have net-snmp installed
first.

SNMP::Info holds all the device-specific code to retrieve data from network
devices via SNMP.  A wide variety of devices are supported.  You may need to
add support for other devices if they do not follow a standard interface.  This
is not too complex.  See SNMP::Info for more details.

You have three different options in installing SNMP::Info

=over

=item [5.2.1] CPAN

    perl -MCPAN -e shell
        o conf prerequisites_policy ask
        install SNMP::Info

=item [5.2.2] From Source

Download newest version from L<http://snmp-info.sourceforge.net>

    tar xvfz SNMP-Info-0.x.tar.gz 
    cd SNMP-Info-0.x
    perl Makefile.PL
    make install

=item [5.2.3] From CVS

If you plan to add or change device support in SNMP::Info to customize Netdisco to your devices,
you should install SNMP::Info this way. 

    make snmp

This will create the SNMP/ directory where SNMP::Info will live.   Periodically you should re-run

    make snmp

To update to the most current CVS version.  For BSD or Solaris systems, use C<gmake> instead
of C<make>

=back

=head3 5.3.  MIBs

MIBs that are required for F<SNMP::Info> are included with Netdisco in the F<mibs/> directory.

They are also available as a separate download on source forge.

=head2 6. GraphViz  (Optional)

GraphViz is used to create the Network Map.

It lives at L<http://www.research.att.com/sw/tools/graphviz/>.

=over

=item [6.1] Download 

=over

=item BSD

For BSD use ports: 

    cd /usr/ports/graphics/graphviz && make install

=item Linux

For Redhat and Mandrake systems you will make sure that a lol of
C<-devel> packages are installed.   If you see errors about not having a PNG
or JPEG library then install the C<-devel> packages as needed. 

    urpmi libjpeg62-devel libpng3-devel

If you get some weird error in build about not having C<intl.la> then
make sure you have the F<gettext> packages installed :

    urpmi gettext-devel

=item Unix

Get the newest version from L<http://www.graphviz.org/pub/graphviz>.
Unarchive and install.

=item Solaris

Follow the UNIX Instructions but ...

Make the JPEG and EXPAT libraries first and when making the JPEG library
make sure you have 

    ./configure --enabled-shared --enabled-static

=item Mac OS X

It is reported to be in C<DarwinPorts> or you can check out L<http://www.phil.uu.nl/~js/graphviz/>.

=back

=item [6.2] True Type Font

Copy a True Type Font file (F<.ttf>) into the Netdisco directory and 
change C<node_font> in F<netdisco.conf> to match.

    cp /path/to/windows/fonts/lucon.ttf /usr/local/netdisco

You can grab F<arial.ttf> or F<lucon.ttf> out of the F<c:\windows\fonts> 
directory of any Windows machine.

=item [6.3] Graph Settings

Review other graph settings in F<netdisco.conf>

=item [6.4] Check Path

Make sure that neato/twopi is in your path, and/or in the crontab path
that creates the graphs.

    which twopi
    which neato

=back

After the Perl Modules step below, 
make sure the Graphviz Perl module got installed

    perldoc GraphViz

NOTE: You can safely ignore all warnings about C<size too small for label>.

=head2 7. Setup Apache

I<Apache2> -- 

Until mod_perl 2.0 is released as stable, Mason will not run under Apache2.  
Netdisco will not run under Apache2 until that point. 

=head3 7.1.  MAC OS X

See the following three links in addition to this document :

L<http://www.oreillynet.com/pub/a/mac/2002/11/05/apache_osx.html>
L<http://www.oreillynet.com/pub/a/mac/2002/12/18/apache_modssl.html>
L<http://www.oreillynet.com/pub/a/mac/2003/02/07/libapreq_update.html>

=head3 7.2.  Mandrake 9.1

Mandrake 9.1 comes with Apache2.  It also has the option
of installing a version of Apache1/mod_perl on a different port
and then reverse-proxying it.   

mod_ssl with Mandrake to come...

=over

=item [7.2.1] Install Apache1

Install Apache1 and Mod_Perl 1 and their development packages :

    urpmi apache-devel-1 mod_perl-devel-1 apache-mod_perl-1 mod_perl-common-1

Mandrake 9.1 - Do this for the DB_File Perl module

    ln -s /usr/include/db1/* /usr/include
    ln -s /usr/lib/libdb1.so.2 /usr/lib/libdb.so

=item [7.2.2] Configure Both Apaches

Mandrake and some Redhats come with two copies of Apache installed.
The mod_perl server sits on a weird port and is reversed proxied by
a normal Apache server.  

Mandrake 9.0 uses two Apache1 servers, while Mandrake 9.1 uses an
Apache2 server that sits in front of the apache1/mod_perl server.

Configuration files for Mandrake live in F</etc/httpd/conf>

In the file F<httpd-perl.conf> add the two C<Include> lines:

    Include /usr/local/netdisco/netdisco_apache.conf
    Include /usr/local/netdisco/netdisco_apache_dir.conf

In the file F<httpd.conf> (F<httpd2.conf> for 9.1) add the final C<RewriteRule> line:

    <IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule ^proxy:.*  -  [F]
    RewriteRule ^(.*\/perl\/.*)$  http://%{HTTP_HOST}:8200$1 [P]
    RewriteRule ^(.*\/cgi-perl\/.*)$  http://%{HTTP_HOST}:8200$1 [P]
    RewriteRule ^(.*\/netdisco\/.*)$  http://%{HTTP_HOST}:8200$1 [P]
    </IfModule>

In the file F<commonhttpd.conf> add the Alias line :

    Alias /netdisco /netdisco/

=item [7.2.3] Restart Apache

    /etc/rc.d/init.d/httpd restart

=back

=head3 7.3.  Apache From Scratch

Install Apache 1.3.x and mod_perl 1.x and mod_ssl

Netdisco is designed to work in a secure (https) or non-secure
environment.  Due to the security and privacy concerned associated with
this data, using a secure server is recommended.

Below is my method if you haven't installed apache and mod_perl before.
I statically compile mod_perl, and mod_ssl then leave the rest of the 
modules as dynamically loadable objects (DSO).

=over

=item [7.3.1] Download and Unarchive

Get Apache from L<http://httpd.apache.org>

Get mod_perl from L<http://perl.apache.org>

Get mod_ssl from L<http://www.modssl.org>

Unarchive all three to the same directory, maybe F</usr/local/src>

=item [7.3.2] Inital Apache Setup

This step makes the framework that mod_ssl and mod_perl need.

 cd apache_1.3*
 ./configure 

No need to make it yet.

=item [7.3.3] mod_ssl

Mod_SSL gives us a secure server (https) for Netdisco to run under.

The OpenSSL library is a prerequirement for mod_ssl and may or may not
already be on your system.  If not :

=over 

=item a. BSD


Installing OpenSSL :

    cd /usr/ports/devel/mm && make install
    cd /usr/ports/security/openssl && make install

Setup mod_ssl :

    cd /path/to/mod_ssl_1.x.x
    SSL_BASE=SYSTEM \
        ./configure \
            --with-apache=../apache_1.3.x \
            --disable_rule=SSL_COMPAT

=item b. RedHat / Mandrake

OpenSSL is installed by default.

You will have to tell the OS to look for the Kerberos libraries
used in this version of OpenSSL:

    ./configure \
        --with-apache=../apache_1.3.x \        
        --disable_rule=SSL_COMPAT
    make C_INCLUDE_PATH=/usr/kerberos/include

Thanks to David Martin for this info.

=item c. By Hand (other OSs)

Follow the instructions in the F<INSTALL> that comes with C<mod_ssl>

 SSL_BASE=/path/to/openssl-0.9.x \
 ./configure \
    --with-apache=../apache_1.3.x \        
    --disable_rule=SSL_COMPAT

=back

=item [7.3.4] mod_perl 

This step sets up mod_perl for this copy of apache :

 cd ../mod_perl-1.x
 /usr/local/bin/perl Makefile.PL \
        APACHE_SRC=../apache_1.3.x/src \
        EVERYTHING=1 \
        DO_HTTPD=1 \
        USE_APACI=1 \
        PREP_HTTPD=1

 make

=item [7.3.5] Apache Again

Now we're ready to make the main apache and install all of 
the above (mod_ssl, mod_perl, and Apache).

 cd ../apache_1.3*
 ./configure \
        --prefix=/usr/local/apache \
        --enable-module=most \
        --enable-shared=max \
        --activate-module=src/modules/perl/libperl.a \
        --with-perl=/usr/local/bin/perl \
        --enable-module=ssl
 make
 make certificate
 make install

=item [7.3.6] Install mod_perl

 cd ../mod_perl*
 make install

=back

=head3 7.4.   Apache Configuration Files 

Add the following lines in your C<httpd.conf>. 

Your C<httpd.conf> will live in C</usr/local/apache/conf> if you installed using my method.

=over

=item [7.4.1] In the Global Section

Add this line B<once> in the end of C<httpd.conf> not in a VirtualHost section.

    Include /usr/local/netdisco/netdisco_apache.conf

=item [7.4.2] No virtualhosts

If you do not have virtual hosts setup and/or you have a main server, add this line right after the 
first include :

    Include /usr/local/netdisco/netdisco_apache_dir.conf

=item [7.4.3] In each VirtualHost

If you have Virtual Hosts or are setting up a secure server, put the following
line in each of them that you want Netdisco turned on for:

If you are not using Virtual Hosts, then add this line under the I<netdisco_apache.conf> line.

    Include /usr/local/netdisco/netdisco_apache_dir.conf

Make sure you have this include line for the secure server virtual host 
B<*:443> at the bottom of F<http.conf>. 

=back

=head3 7.5.  Mason Data Directory

Set the mason data directory writable to the apache user that does the 
requests.

Assuming C<nobody> is the user that apache requests run this as C<root> :

    mkdir /usr/local/netdisco/mason
    chown nobody.netdisco /usr/local/netdisco/mason

The name of the user is listed in C<httpd.conf> under the C<User> directive. 

Note: Some Linux distributions such as Redhat 6.x install mod_perl as 
a Dynamic Shared Object (DSO).  This is known to be unstable, especially
with Mason.   Compile mod_perl statically using the method listed
above.

=head2 8. Perl Modules and Mason

Below is a list of required modules for Netdisco, freely available from
CPAN (http://www.cpan.org).   Many of these modules have prerequisite 
modules.   


=head3 8.1.  Install required Perl modules from CPAN

Use the CPAN module that comes with Perl to install the modules
and their prerequisites automatically:

    perl -MCPAN -e shell

        o conf prerequisites_policy ask
        install Digest::MD5
        install Bundle::DBI
        install Apache::DBI
        install DBD::Pg
        install DB_File      (for Apache::Session)
        install Apache::Session
        install Apache::Test (for Apache::Request, you may need to do a 'force install')
        install Apache::Request
        install HTML::Entities
        install HTML::Mason
        install MasonX::Request::WithApacheSession
        install Graph
        install GraphViz     (you may need to do a 'force install')
        install Compress::Zlib (probably already have this one)

Some of these you will probably already have installed. Others you may need to force 
with C<force install ModuleName>.  B<Do Not> include the comments in (parens)!

=head3 8.2.  Perl Location header in executables.

If you have Perl installed in C</usr/bin>, make sure that F<netdisco> and F<bin/doc_munge>
have the correct location for Perl listed at the very top of the file.

=head2 9. Netdisco Configuration

=over

=item [9.1] netdisco.conf

Modify F<netdisco.conf> to match your site.  

See F<README> for detailed configuration descriptions.

=item [9.2] netdisco_apache.conf

Change settings on lines:

    session_user_name
    session_password
    session_cookie_domain

=item [9.3] netdisco.crontab

Change C<!!center_network_device_here!!> to a network device that is well connected to the main
segment by CDP.


=item [9.4] Add a user in Netdisco

This is a user inside the Netdisco database that will be your Web Admin User

    /usr/local/netdisco/netdisco -u username

Add more users from the web C<Admin Panel> once Netdisco is up and running.

=item [9.5] Make Documentation (CVS Versions Only)

This step is only necessary if you have installed from CVS.

=over 

=item i. Perl Location

Make sure that the C<POD2TEXT>  lines in F<Makefile> point to where your Perl binaries
are installed.

=item ii. Create Docs

 cd /usr/local/netdisco && gmake doc

=back

=item [9.6] Change Permissions on Config files

Since the config files contain SNMP community strings and database passwords,
you must make them only available to the administrators for security.

 chgrp netdisco /usr/local/netdisco/*.conf
 chmod 660 /usr/local/netdisco/*.conf

=back

=head2 10. OUI Database

The Organizationally Unique Identifier (OUI) database allows Netdisco to
identify the manufacture of a network card using the first 24 bits of a MAC
address.

Run the following command to import the contents of F<oui.txt> into your
database.

    cd /usr/local/netdisco
    netdisco -O

=head3 [10.1] Updating oui.txt (Optional)

The database of OUIs is needed by Netdisco and is available from the IEEE.

If you have lynx installed you can install the OUI database by:

    cd /usr/local/netdisco
    make oui

(gmake for BSD/Solaris)

Or do this by hand:

   1. Download oui.txt from http://standards.ieee.org/regauth/oui/
   2. Run netdisco -O

A note about Make versions. The Makefile is a GNU Make version file. In BSD you may have to type gmake.

=head2 11. Start Apache

Now that you have everything setup, (re)start the 
web-server.

Check Apache's F<error_log> for possible errors.

=over

=item [11.1] HomeGrown Copies of Apache


    /usr/local/apache/bin/apachectl start

=item [11.2] Used the Apache installed by Mandrake


    /etc/rc.d/init.d/httpd restart


=back

Also, make sure that Apache starts on its own
at reboot.

=head2 12. Discover a Device in Netdisco

Pick a device that you can access with the command C<snmpwalk>.  
Tell Netdisco to discover that device:

    cd /usr/local/netdisco
    ./netdisco -d devicename

Make sure that this step actually works.  This is a good metric that you have 
now installed Netdisco correctly.  Add the I<-D> flag to get copious debugging info.

=head2 13. Create Network Topology

See F<README> for a description of I<Topology Information>.  

If your network is CDP aware, pick a device that you consider close to the center of the 
network and start an auto-discovery from there:

    cd /usr/local/netdisco
    ./netdisco -r device_name_or_ip_number_here

If your network is I<not> CDP friendly, then see F<README> for how to
use the manual topology file F<netdisco-topology.txt>.

You MUST supply Netdisco with a working topology or MAC addresses will show
up on uplink ports instead of end ports.

=head2 14. Test Web Side

First restart Apache so that netdisco will see the changes that you have made
in F<netdisco.conf>.  Note that a I<graceful> restart will not re-read the configuration
file.  A full restart is required.

    /usr/local/apache/bin/apachectl restart

Point a browser to I</netdisco> on the server you have Netdisco installed on. 
If everything is working you should be able to login with the user name and password
you added in Step 10.  You should also be able to access the Admin Panel.

    http://localhost/netdisco

If you have problems, check the F<error_log> of apache for messages.

    tail /usr/local/apache/logs/error_log

=head2 15. Add Cron Jobs

Once you're sure Netdisco is setup correctly, modify
F<netdisco.crontab>.  Change the _center_device_ to one of your
core routers or switches.

    vi netdisco.crontab

Now set the crontab to the C<netdisco> user.

    su - -c "crontab -u netdisco /usr/local/netdisco/netdisco.crontab"

You may want to fine-tune these jobs to your network.

=head2 16. Start Admin Daemon

The admin deaemon performs administration jobs that are requested from the
web front-end.  See F<README> for a description of the admin daemon.  

    su - netdisco -c "/usr/local/netdisco/netdisco -p start"

The daemon will be respawned daily in the Cron job listed above. 

If you would like the Daemon to be started upon bootup, then add
the following line to your F</etc/rc.d/rc.local> file :

    su netdisco -c "/usr/local/netdisco/netdisco -p start"

=head1 SUCCESS

Now that you have spent ten hours of your life installing this go drink a Beer,
you deserve it. 

Once you have or have not succeeded, come join the Netdisco User's mailing list at 
L<http://netdisco.org> and pass on any hints you may have in the INSTALL process.

It's a good place to keep up on new features and releases, and it's B<the>
place to ask any questions. 

=head2 Donations

Netdisco is developed as a hobby and is not a commercial venture. 

If you find Netdisco useful please consider donating to its developer.  Check
out L<http://netdisco.org> for a Source Forge donation page and Amazon
wish list.

=cut
