=head1 NAME

Netdisco UPGRADE - Instructions on Upgrading between versions.

=head1 AUTHOR

Max Baker

=head1 SUPPORT

See INSTALL or README or L<http://netdisco.org>

=head1 UPGRADING

Here are some hints for upgrading between versions of Netdisco.

There are two methods of upgrading.  Please backup the database 
(see below) before continuing.

=over

=item 1. Apply Patch

Each version starting with version 0.93 will have a C<.patch> that you can apply
to get the newest version.   If you have a lot of site customizations, this 
might be the best way for you.  Be prepared to fix any conflicting merges that
may happen.  If you can't handle a little code-diving, this may not be the method
for you. 

You will also need to get the newest SNMP::Info and possibly run a C<.sql> file 
to make changes to the database structure. 

=item 2. Fresh Upgrade

The B<best way> is to back everything up, move the configuration
files out of the way and then follow F<INSTALL> for all but the
database steps.

Then change the configuration files back to match.

You B<DO NOT> wipe the database contents for an upgrade.  But just in case, you will have
of course made a backup by now. 

=back

=head1 VERSION SPECIFIC NOTES

=over

=item v0.92 -> 0.93

=over

=item GraphViz 0.10

You may want to install this latest version of GraphViz

=item Database Upgrades

For some of the new features, fields have been added to some
of the database tables.  A F<.sql> file has been made to make
the changes for you.   Please run :

 cd /usr/local/netdisco/sql
 ./pg_run 


=back

=item v0.91 -> 0.92

Make sure you run C<Database Cleanup>  or C<-K> when you 
are done upgrading.  The bug where the MAC address of switch
ports showing up on their own port has been fixed.  SNMP::Info
Version 0.7 required.

=item v0.90 -> 0.91

=over

=item netdisco_apache.conf

Double check that your copy of netdisco_apache.conf has the 
settings right for all the C<session_*> directives.

=item GraphViz

Make sure you have GraphViz 0.9 installed.

=back

=back

=head1 APPLICATIONS

=head2 Apache / Mod_perl

You shouldn't have to upgrade apache, but now would be a good time to
see if there are any security upgrades to apache or mod_perl.

=head2 SNMP::Info

When upgrading to any version, please make sure you have the
newest version of SNMP::Info installed (at least 0.8) :

=over

=item CVS Version

To update a CVS version of SNMP::Info : 

    cd /usr/local/netdisco/SNMP
    cvs update

=item CPAN Version

To update a version installed by CPAN :

    perl -MCPAN -e shell
    install SNMP::Info

=item Manual Install Version

Download the newest version from CPAN or L<http://snmp-info.sourceforge.net>
and install.

=back

=head2 General Upgrade Procedures

=over 

=item Read INSTALL

Read the INSTALL file that comes with the new version to see
what has changed.  Make sure you have all the Requirements
listed.

=item Backup Database

For any version you will want to make backup copies of all your 
data first.  

    cd /usr/local/netdisco/sql
    ./pg_back
    scp db_back*.gz somesafehost:

=item Backup Configuration Files

Make backups of all your files.

    tar cvf - -C /usr/local netdisco | gzip > netdisco-back.tgz
    scp netdisco-back.tgz somesafehost:
    cp /usr/local/netdisco/*.conf /path/to/some_where_safe
    cp /usr/local/netdisco/*.txt  /path/to/some_where_safe

=item Install on top of existing Netdisco

Put the new files in your F<netdisco/> directory 

    cp -R /path/to/netdisco-new-0.999 /usr/local/netdisco

=item [Optional] Upgrade Perl Modules

Following the procedures in F<INSTALL>, now would be a good time
to upgrade all the required Perl modules.  

This step is optional, unless a certain Perl module is listed for 
your version.

=item Check Permissions

Make sure the permissions are set to let the web user
read the F<html/> directory and write to the F<mason/> directory.

=item Modify the Configuration Files

New options are always being added to the config files and 
Netdisco.  It's usually a lot cleaner to modify the new config
file that comes with Netdisco than try to add the new features
to the old one.  This helps get rid of old bugs too.

=item Restart Apache

You must do a full restart on apache (not a C<graceful> or C<restart>) so that Netdisco
will use the newly installed version of F<netdisco.pm>. 

    /usr/local/apache/bin/apachectl stop
    /usr/local/apache/bin/apachectl start

=item Restart Admin Daemon

You need to restart the admin daemon to run on the new copy of Netdisco.

    su - netdisco -c "/usr/local/netdisco -p restart"
    
=item Reload Crontab

Review F<netdisco.crontab> and reload it for the C<netdisco> user.

    su 
    crontab -u netdisco /usr/local/netdisco/netdisco.crontab

=back
