#!/bin/sh
# pg_all - Max Baker 
# 	run pg_run on all the tables in this dir.
# $Id$

FILES="admin.sql device.sql device_ip.sql device_port.sql device_port_log.sql \
       device_port_ssid.sql \
       log.sql node.sql node_ip.sql node_nbt.sql oui.sql sessions.sql \
       subnets.sql user_log.sql users.sql"

rm -f pg_all.input
touch pg_all.input

for file_name in $FILES ;
do	
	echo "[ $file_name ]"
    cat $file_name >> pg_all.input
	echo ""
done;

./pg_run pg_all.input
