#!/bin/sh
# Max Baker <max@warped.org>
# Postgresql setup shell script

# Change these to match your setup
SYSDBUSER=pgsql
DB=disc

CREATEUSER="createuser --createdb --no-adduser --pwprompt $DB"

echo "--> Creating User $DB."
echo "Choose a password just for this new database user."
su $SYSDBUSER -c "$CREATEUSER"

echo ""
echo "Creating Database $DB.  Use the Password used above."
createdb --username=$DB --password $DB "Storage and stuff"

